## JUCE Modules Configuration
# This file sets up JUCE modules for the DemoTape project

# Specify JUCE modules to include
set(JUCE_MODULES
    juce_audio_basics
    juce_audio_devices
    juce_audio_formats
    juce_audio_plugin_client
    juce_audio_processors
    juce_audio_utils
    juce_core
    juce_data_structures
    juce_events
    juce_graphics
    juce_gui_basics
    juce_gui_extra
    juce_opengl
)

# Function to add JUCE module
function(add_juce_module TARGET MODULE_NAME)
    set(MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../JUCE/modules/${MODULE_NAME}")
    
    if(EXISTS "${MODULE_PATH}")
        message(STATUS "Adding JUCE module: ${MODULE_NAME}")
        
        # Add include path
        target_include_directories(${TARGET} PRIVATE "${MODULE_PATH}")
        
        # Add module definition
        string(TOUPPER "${MODULE_NAME}" MODULE_NAME_UPPER)
        target_compile_definitions(${TARGET} PRIVATE "JUCE_MODULE_AVAILABLE_${MODULE_NAME_UPPER}=1")
        
        # Find source files
        file(GLOB_RECURSE MODULE_SOURCES "${MODULE_PATH}/*.cpp")
        file(GLOB_RECURSE MODULE_HEADERS "${MODULE_PATH}/*.h")
        
        # Add sources to target
        target_sources(${TARGET} PRIVATE ${MODULE_SOURCES})
    else()
        message(WARNING "JUCE module not found: ${MODULE_NAME}")
    endif()
endfunction()

# Generate JuceHeader.h if it doesn't exist
function(generate_juce_header TARGET)
    set(HEADER_PATH "${CMAKE_CURRENT_SOURCE_DIR}/JuceLibraryCode/JuceHeader.h")
    
    if(NOT EXISTS "${HEADER_PATH}")
        message(STATUS "Generating JuceHeader.h")
        
        file(WRITE "${HEADER_PATH}" "#pragma once\n\n")
        file(APPEND "${HEADER_PATH}" "// This file was auto-generated by CMake\n\n")
        
        foreach(MODULE_NAME ${JUCE_MODULES})
            file(APPEND "${HEADER_PATH}" "#include <${MODULE_NAME}/${MODULE_NAME}.h>\n")
        endforeach()
        
        file(APPEND "${HEADER_PATH}" "\n// Using SDL defines (for Clang)\n")
        file(APPEND "${HEADER_PATH}" "#if !defined (JUCE_DONT_DECLARE_PROJECTINFO)\n")
        file(APPEND "${HEADER_PATH}" "namespace ProjectInfo\n")
        file(APPEND "${HEADER_PATH}" "{\n")
        file(APPEND "${HEADER_PATH}" "    const char* const  projectName    = \"DemoTape\";\n")
        file(APPEND "${HEADER_PATH}" "    const char* const  companyName    = \"YourCompany\";\n")
        file(APPEND "${HEADER_PATH}" "    const char* const  versionString  = \"1.0.0\";\n")
        file(APPEND "${HEADER_PATH}" "    const int          versionNumber  = 0x10000;\n")
        file(APPEND "${HEADER_PATH}" "}\n")
        file(APPEND "${HEADER_PATH}" "#endif\n")
    endif()
endfunction() 